baseURL = 'https://gregpuzzles1.github.io/blog_hugo/'
locale = 'en-us'
title = "Tech Trail Pulse"
theme = "blowfish"

[menus]
	[[menus.main]]
		name = "About"
		pageRef = "/about"
		weight = 10

	[[menus.main]]
		name = "Reading Trail"
		pageRef = "/reading-list"
		weight = 20

	[[menus.main]]
		name = "Puzzlemania"
		pageRef = "/puzzlemania"
		weight = 30

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true

[params]
	logo = "favicon.PNG"
	copyright = "&copy; { year } Greg Christian - [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)"

[params.homepage]
	layout = "page"
	showRecent = false